replicaCount: 2

image:
  repository: 586855150137.dkr.ecr.eu-west-1.amazonaws.com/eneco/wallace-sre-challenge
  pullPolicy: IfNotPresent
  tag: 0.4

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080

env:
  featureBranch: preview-dev

envFrom:
  - configMapRef:
      name: api-environment
  - secretRef:
      name: db-password

ingress:
  enabled: false
  className: alb
  annotations:
    kubernetes.io/ingress.class: alb
  hosts:
    - host: api.eneco.nl
      paths:
        - path: /
          pathType: Prefix
  tls:
   - secretName: eneco-api-cert-manager-tls
     hosts:
       - api.eneco.nl

resources: 
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: 8080
readinessProbe:
  httpGet:
    path: /
    port: 8080

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetMemoryUtilizationPercentage: 80
